### ISSUE TITLE
What's supposed to be in /Config?

### ISSUE THREAD

**Issue by holli-holzer** [saiftynet/EZPWC#1]
See https://i.imgur.com/7Mzf4j8.png

**Comment by saiftynet** [comment]
![Imgur](https://i.imgur.com/7Mzf4j8.png)

Config uses a crude way to store data for easy loading and storing configuration data.
Probably better done using another method (e.g. Storable/Dumper etc).  Happy for your advice.
It contains 1) the working directory location 2) the repo name and repo owner in Github (perlweeklychallenge-club and manwar) 3) your github user name 4) whether you have a Github fork 
 setup, 5) whether a clone has been downloaded 6) the current week number 7) the latest tasks and one or two other things.

It is formatted like the contents of a hash, so that it can be easily loaded using %config= do <ConfigFileName>.  But as I say...may be more robustly done using another methods.  Now I use Linux, and my setup may be different from yours...so your help in  ironing out these issues would be helpful.

**Comment by saiftynet** [comment]
Maybe the problem is creating directories or sub-directories.  It may be also thatthe path should be use escapes backslashes for the path e.g. D:\\\\projecte\\\\Perl6\\\\perlweeklychallenge-club.  Note that EZPWC clones the git repo into your working directory.  So there will be a folder called perlweeklychallenge-club created in your working directory, containing the files from your fork.

**Comment by holli-holzer** [comment]
The problem is your `loadConfig` sub. It doesn't check for the Config-file not existing. You have

```
sub loadConfig{
	if (-e "$workingDirectory/Config") {
		if (%config=do "$workingDirectory/Config" ){
			print "Config successfully loaded\n";
		}
		else{
			print "Failed to load config, continuing with defaults\n";
			unlink ($config{workingDirectory}."/Config");
			%config=(
                            # ...     
			);
		}
	}
}
``` 

But what you probably meant is

```
sub loadConfig{
	if (-e "$workingDirectory/Config") {
		if (%config=do "$workingDirectory/Config" ){
			print "Config successfully loaded\n";
			return;
		}
	}

	print "Failed to load config, continuing with defaults\n";
	unlink ($config{workingDirectory}."/Config");
	%config=(
		# ...
	);
}
```

That way it covers both "not existing" and "cannot load for whatever reason"

**Comment by saiftynet** [comment]
Makes sense, thanks for that mate. will amend accordingly
